### ISSUE TITLE
add "technology icons" for links

### ISSUE THREAD

**Issue by rilian** [rilian/newsletter#26]
![postgres-f83842befe0105002f9867f2d937a68b](https://cloud.githubusercontent.com/assets/155563/10564007/fa1822d2-75aa-11e5-8f00-7dc11a86265d.png)
<img width="262" alt="scr 2015-10-18 at 15 14 32" src="https://cloud.githubusercontent.com/assets/155563/10564008/fa39937c-75aa-11e5-9da3-39d30bb5ed57.png">
etc

display them in a 24x24 square nearby the link

**Comment by sudodoki** [comment]
1) Should decide, whether they should be lib/framework specific, like [these](http://svgporn.com) or should be highlevel (ruby, js, db, mobile, etc). 
2) Should decide, what should happen, when multiple icons can apply (working w/ db using ruby).

**Comment by sudodoki** [comment]
Could also start w/ tags or do merged icons (db + ruby -> half db, half ruby logo).

**Comment by rilian** [comment]
smth like this

<img width="596" alt="scr 2015-10-18 at 16 27 41" src="https://cloud.githubusercontent.com/assets/155563/10564251/386dd9b4-75b5-11e5-8cbb-cac17cf3fca5.png">

**Comment by rilian** [comment]
tags are added :)
