### ISSUE TITLE
Design improvements

### ISSUE THREAD

**Issue by marina-marina** [rilian/newsletter#9]
This is what we have now: http://prntscr.com/8dlezg
This is how we should change it: http://prntscr.com/8dlher
On the screenshot I've added more line-height and margins on list items, more margins on heading and form, right margin after the input and centered the form.

**Comment by rilian** [comment]
thanks - would you like to make a PR with this small fix? :+1:

**Comment by rilian** [comment]
i think this is fixed now (subscription form)
